telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://4bd9-95-32-21-229.eu.ngrok.io"
  bot-name: "learnwordseveryday_bot"
  bot-token: ${LEARN_WORDS_BOT_TOKEN}
spring:
  redis:
    database: 0
    host: "ec2-75-101-159-138.compute-1.amazonaws.com"
    port: 21880
    password: ${REDIS_PASSWORD}
    ssl: true
server:
  port: 5050